// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropfactMap.Models;

#nullable disable

namespace PropfactMap.Migrations
{
    [DbContext(typeof(AddressPointContext))]
    [Migration("20230212152634_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PropfactMap.Models.AddressPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AddressType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Angle")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointX")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PointY")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("PropAddrL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropAddrL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("X")
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("Y")
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.ToTable("AddressPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
